version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    volumes:
      - ./mysqldb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - mysqldb

  app:
    build:
      context: '.'
      dockerfile: Dockerfile
    container_name: system_sales
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysqldb
    networks:
      backend:
        aliases:
          - system_sales

networks:
  backend:
    name: backend-network
